spring:
  security:
    user:
      name: techUser
      password: techUser
  application:
    name: messages-service
  zipkin:
    base-url: http://127.0.0.1:9411
  rabbitmq:
    addresses: 127.0.0.1:5672
server:
  port: '9091'
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    email: messages-queue
  routing-keys:
    internal-email: internal.email.routing-key