spring:
  security:
    user:
      name: techUser
      password: techUser
  application:
    name: messages-service
server:
  port: '9091'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true