ALTER TABLE USERS
    ADD COLUMN FACEBOOK_NOTIFICATION BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE USERS
    ADD COLUMN SMS_NOTIFICATION BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE USERS
    ADD COLUMN SLACK_NOTIFICATION BOOLEAN NOT NULL DEFAULT FALSE;
