CREATE TABLE LECTURES
(
    ID            LONG         SERIAL NOT NULL PRIMARY KEY,
    NAME          VARCHAR(255) NOT NULL,
    THEMATIC_PATH VARCHAR(255) NOT NULL,
    START_TIME    TIME         NOT NULL
);

CREATE TABLE USERS
(
    ID                 LONG SERIAL NOT NULL PRIMARY KEY,
    LOGIN              VARCHAR(255),
    EMAIL              VARCHAR(255),
    ENCRYPTED_PASSWORD VARCHAR(255)
);

ALTER TABLE USERS
    ADD UNIQUE ("LOGIN");
ALTER TABLE USERS
    ADD UNIQUE ("EMAIL");

CREATE TABLE ROLES
(
    ID   LONG         SERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE USER_LECTURE
(
    ID         LONG SERIAL NOT NULL PRIMARY KEY,
    USER_ID    LONG NOT NULL,
    LECTURE_ID LONG NOT NULL
);

ALTER TABLE USER_LECTURE
    ADD CONSTRAINT FK_USER_LECTURE_USER_ID
        FOREIGN KEY ("USER_ID")
            REFERENCES USERS (ID);
ALTER TABLE USER_LECTURE
    ADD CONSTRAINT FK_USER_LECTURE_LECTURE_ID
        FOREIGN KEY ("LECTURE_ID")
            REFERENCES LECTURES (ID);

CREATE TABLE USERS_ROLES
(
    ID      LONG SERIAL NOT NULL PRIMARY KEY,
    USER_ID LONG NOT NULL,
    ROLE_ID LONG NOT NULL
);

ALTER TABLE USERS_ROLES
    ADD CONSTRAINT FK_USERS_ROLES_ROLE_ID
        FOREIGN KEY ("ROLE_ID")
            REFERENCES ROLES (ID);
ALTER TABLE USERS_ROLES
    ADD CONSTRAINT FK_USERS_ROLES_USER_ID
        FOREIGN KEY ("USER_ID")
            REFERENCES USERS (ID);

CREATE SEQUENCE HIBERNATE_SEQUENCE
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999
    START WITH 1
    NO CYCLE;